-- Enable the citext extension
CREATE EXTENSION IF NOT EXISTS citext;

-- Create a table using CITEXT for case-insensitive text columns
CREATE TABLE citext_table (
    id SERIAL PRIMARY KEY,
    username CITEXT NOT NULL UNIQUE,
    email CITEXT NOT NULL UNIQUE,
    display_name VARCHAR(100),
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert 50 sample users with unique usernames and emails
INSERT INTO citext_table (username, email, display_name, bio) VALUES
    ('JohnDoe', 'john.doe@example.com', 'John Doe', 'Software developer from New York'),
    ('AliceSmith', 'alice.smith@example.org', 'Alice Smith', 'Data scientist and coffee lover'),
    ('RobertJones', 'robert.jones@example.net', 'Robert Jones', 'Cybersecurity expert'),
    ('EmilyBrown', 'emily.brown@example.com', 'Emily Brown', 'Graphic designer and artist'),
    ('MichaelWilson', 'michael.wilson@example.org', 'Michael Wilson', 'Marketing strategist'),
    ('SarahDavis', 'sarah.davis@example.net', 'Sarah Davis', 'Environmental scientist'),
    ('DavidMiller', 'david.miller@example.com', 'David Miller', 'Financial analyst'),
    ('JenniferGarcia', 'jennifer.garcia@example.org', 'Jennifer Garcia', 'Human resources manager'),
    ('ChristopherLee', 'christopher.lee@example.net', 'Christopher Lee', 'Software architect'),
    ('AmandaWhite', 'amanda.white@example.com', 'Amanda White', 'Pharmaceutical researcher'),
    ('MatthewHarris', 'matthew.harris@example.org', 'Matthew Harris', 'Mechanical engineer'),
    ('LauraMartinez', 'laura.martinez@example.net', 'Laura Martinez', 'Education consultant'),
    ('DanielRodriguez', 'daniel.rodriguez@example.com', 'Daniel Rodriguez', 'Sales manager'),
    ('NicoleAnderson', 'nicole.anderson@example.org', 'Nicole Anderson', 'Legal counsel'),
    ('RyanThompson', 'ryan.thompson@example.net', 'Ryan Thompson', 'IT security consultant'),
    ('StephanieClark', 'stephanie.clark@example.com', 'Stephanie Clark', 'Graphic design director'),
    ('KevinRivera', 'kevin.rivera@example.org', 'Kevin Rivera', 'Aerospace engineer'),
    ('KatherineSanchez', 'katherine.sanchez@example.net', 'Katherine Sanchez', 'Biotechnology researcher'),
    ('AndrewMoore', 'andrew.moore@example.com', 'Andrew Moore', 'Data science lead'),
    ('JessicaHill', 'jessica.hill@example.org', 'Jessica Hill', 'UX/UI designer'),
    ('BrandonKing', 'brandon.king@example.net', 'Brandon King', 'Digital marketing director'),
    ('AshleyScott', 'ashley.scott@example.com', 'Ashley Scott', 'Healthcare administrator'),
    ('EthanGreen', 'ethan.green@example.org', 'Ethan Green', 'Product manager'),
    ('OliviaAdams', 'olivia.adams@example.net', 'Olivia Adams', 'Public relations specialist'),
    ('WilliamTaylor', 'william.taylor@example.com', 'William Taylor', 'Cloud architect'),
    ('SophiaMartin', 'sophia.martin@example.org', 'Sophia Martin', 'Research scientist'),
    ('JamesWright', 'james.wright@example.net', 'James Wright', 'Business analyst'),
    ('IsabellaNguyen', 'isabella.nguyen@example.com', 'Isabella Nguyen', 'Product designer'),
    ('BenjaminLopez', 'benjamin.lopez@example.org', 'Benjamin Lopez', 'Software engineer'),
    ('MiaPatel', 'mia.patel@example.net', 'Mia Patel', 'Data analyst'),
    ('AlexanderChen', 'alexander.chen@example.com', 'Alexander Chen', 'Mobile developer'),
    ('EmmaKim', 'emma.kim@example.org', 'Emma Kim', 'UI/UX researcher'),
    ('DanielPark', 'daniel.park@example.net', 'Daniel Park', 'DevOps engineer'),
    ('AvaGonzalez', 'ava.gonzalez@example.com', 'Ava Gonzalez', 'System administrator'),
    ('HenryWilson', 'henry.wilson@example.org', 'Henry Wilson', 'Network engineer'),
    ('LilyCohen', 'lily.cohen@example.net', 'Lily Cohen', 'Quality assurance'),
    ('LucasRamsey', 'lucas.ramsey@example.com', 'Lucas Ramsey', 'Frontend developer'),
    ('ZoeyBaker', 'zoey.baker@example.org', 'Zoey Baker', 'Backend developer'),
    ('GabrielCruz', 'gabriel.cruz@example.net', 'Gabriel Cruz', 'Full stack developer'),
    ('VictoriaLi', 'victoria.li@example.com', 'Victoria Li', 'Machine learning engineer'),
    ('JulianFoster', 'julian.foster@example.org', 'Julian Foster', 'Security analyst'),
    ('PenelopeCox', 'penelope.cox@example.net', 'Penelope Cox', 'Database administrator'),
    ('CalebMorgan', 'caleb.morgan@example.com', 'Caleb Morgan', 'Systems architect'),
    ('HannahRoss', 'hannah.ross@example.org', 'Hannah Ross', 'Technical lead'),
    ('ChristianGray', 'christian.gray@example.net', 'Christian Gray', 'Project manager'),
    ('EllaHughes', 'ella.hughes@example.com', 'Ella Hughes', 'Scrum master'),
    ('LiamBarnes', 'liam.barnes@example.org', 'Liam Barnes', 'Product owner'),
    ('AudreyFord', 'audrey.ford@example.net', 'Audrey Ford', 'Release engineer'),
    ('OwenCooper', 'owen.cooper@example.com', 'Owen Cooper', 'Site reliability engineer'),
    ('ScarlettWard', 'scarlett.ward@example.org', 'Scarlett Ward', 'Infrastructure engineer');